Repository googleapis/python-channel, pull requests merged in 2021-04, with the labels that each got.

#21 chore: start tracking obsolete files
  synth.metadata
Labels: api: cloudchannel, cla: yes, context: full

#22 chore: migrate to owl-bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: api: cloudchannel, cla: yes

#25 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudchannel, automerge, cla: yes

#30 chore(revert): revert preventing normalization
  setup.py
Labels: api: cloudchannel, cla: yes
